import { NextRequest, NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { sendEmail } from '@/lib/email/send'
import { ticketCreatedCustomer } from '@/lib/email/templates'
import { rateLimit, getClientIp } from '@/lib/rate-limit'
import { executeAutomations } from '@/lib/automations/engine'
import { z } from 'zod'

const createTicketSchema = z.object({
  name: z.string().min(3),
  email: z.string().email(),
  phone: z.string().optional(),
  product_id: z.string().min(1),
  category_id: z.string().min(1),
  title: z.string().min(1),
  description: z.string().min(20),
  ai_messages: z
    .array(
      z.object({
        role: z.string(),
        content: z.string(),
        confidence: z.number().optional(),
      })
    )
    .optional(),
})

export async function POST(request: NextRequest) {
  try {
    const ip = getClientIp(request)
    const { allowed } = rateLimit(`tickets:${ip}`, { limit: 5, windowSeconds: 60 })
    if (!allowed) {
      return NextResponse.json(
        { success: false, error: 'Muitas requisicoes. Aguarde um momento.' },
        { status: 429 }
      )
    }

    const supabase = createAdminClient()
    const body = await request.json()
    const parsed = createTicketSchema.safeParse(body)

    if (!parsed.success) {
      const fieldErrors = parsed.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ')
      console.error('Ticket validation failed:', fieldErrors)
      return NextResponse.json(
        { success: false, error: `Dados invalidos: ${fieldErrors}` },
        { status: 400 }
      )
    }

    const { name, email, phone, product_id, category_id, title, description, ai_messages } = parsed.data

    // Find or create customer
    let customerId: string
    const { data: existingCustomer } = await supabase
      .from('customers')
      .select('id')
      .eq('email', email)
      .single()

    if (existingCustomer) {
      customerId = existingCustomer.id
      // Update name/phone if changed
      await supabase
        .from('customers')
        .update({ name, phone })
        .eq('id', customerId)
    } else {
      const { data: newCustomer, error: customerError } = await supabase
        .from('customers')
        .insert({ name, email, phone })
        .select('id')
        .single()

      if (customerError || !newCustomer) {
        throw new Error('Erro ao criar cliente')
      }
      customerId = newCustomer.id
    }

    // Create ticket (ticket_code and access_token are generated by triggers)
    const { data: ticket, error: ticketError } = await supabase
      .from('tickets')
      .insert({
        customer_id: customerId,
        product_id,
        category_id,
        title,
        description,
        status: 'open',
        priority: 'medium',
        source: 'portal',
      })
      .select('id, ticket_code, access_token')
      .single()

    if (ticketError || !ticket) {
      throw new Error('Erro ao criar ticket')
    }

    // Save AI messages as first messages if they exist
    if (ai_messages && ai_messages.length > 0) {
      const messagesToInsert = ai_messages.map((msg) => ({
        ticket_id: ticket.id,
        sender_type: msg.role === 'user' ? 'customer' : 'ai',
        content: msg.content,
        is_internal_note: false,
      }))

      const { error: messagesError } = await supabase.from('messages').insert(messagesToInsert)
      if (messagesError) {
        console.error('Error inserting AI messages:', messagesError)
      }
    }

    // Log activity
    const { error: activityError } = await supabase.from('activity_log').insert({
      ticket_id: ticket.id,
      actor_type: 'customer',
      action: 'created',
      details: { source: 'portal' },
    })
    if (activityError) {
      console.error('Error logging activity:', activityError)
    }

    // Send email notification to customer (non-blocking)
    const emailData = ticketCreatedCustomer({
      customerName: name,
      ticketCode: ticket.ticket_code,
      accessToken: ticket.access_token,
      title,
    })
    sendEmail({
      to: email,
      subject: emailData.subject,
      html: emailData.html,
      ticketId: ticket.id,
      template: 'ticket_created',
    }).catch(() => {})

    // Execute automations (non-blocking)
    executeAutomations({
      ticket_id: ticket.id,
      trigger_type: 'ticket_created',
      data: { status: 'open', priority: 'medium', product_id, category_id },
    }).catch(() => {})

    return NextResponse.json(
      {
        success: true,
        data: {
          ticket_code: ticket.ticket_code,
          access_token: ticket.access_token,
        },
      },
      { status: 201 }
    )
  } catch (error) {
    console.error('Error creating ticket:', error)
    return NextResponse.json(
      { success: false, error: 'Erro ao criar ticket' },
      { status: 500 }
    )
  }
}
